In [99]:
class MaxHeap:
    List = []

    def insert(number):
        MaxHeap.List.append(number)
        
    def delete(number):
        MaxHeap.List.remove(number)
        
    def get_max():
        Max = 0
        for i in MaxHeap.List:
            if i>Max:
                Max = i
        return Max
    
    
MaxHeap.insert(10)
MaxHeap.insert(12)
MaxHeap.insert(16)
MaxHeap.insert(1)
MaxHeap.insert(7)
MaxHeap.insert(9)
print(MaxHeap.List)
MaxHeap.delete(12)
print(MaxHeap.List)
print(MaxHeap.get_max())



[10, 12, 16, 1, 7, 9]
[10, 16, 1, 7, 9]
16


In [100]:
def get_fibonacci(n):
    Sum = 1
    series = [1]
    for i in range(n):
        series.append(Sum)
        Sum+=series[i]
    return Sum   

print(get_fibonacci(10))

144


In [101]:
def division(dividend, divisor):
    if divisor == 0:
        return "Cannot divide by zero!"
    else:
        return dividend/divisor
    
print(division(10,5))

2.0


In [104]:
def calculator(num1,operation,num2):
    if operation == "+":
        return num1+num2
    elif operation == "-":
        return num1-num2
    elif operation == "*":
        return num1*num2
    elif operation == "/":
        return num1/num2
    else:
        return "not a correct operator"

        
print(calculator(40,"*",3))
print(calculator(20,"&",4))

120
not a correct operator


In [105]:
import random as rd

def random_password_generator():
    length = rd.randint(8,20)
    password = []
    Final = ""
    Choice = ["Uppercase","Lowercase","numbers","special characters"]
    for i in range(length):
        choice = rd.choice(Choice)
        if choice == "Uppercase":
            password.append(chr(rd.randint(65,90)))
        elif choice == "Lowercase":
            password.append(chr(rd.randint(97,122)))
        elif choice == "numbers":
            password.append(chr(rd.randint(48,57)))
        else:
            password.append(chr(rd.randint(33,47)) or chr(rd.randint(58,64)) or chr(rd.randint(91,96)) or chr(rd.randint(123,126)))
    for j in password:
        Final+=j
    return Final

print(random_password_generator())
print(random_password_generator())
print(random_password_generator())
print(random_password_generator())
print(random_password_generator())
print(random_password_generator())

'!0rG-MA/X*.$bKEI7
2oq9"75m-bF+K#Q/zU8c
m$BIsF+'8F"QR
JH&J65/PG+pc9/q
H)F4k65!Cg3(8/
III35(S-$.0


In [107]:
import numpy as np

def transpose(matrix):
    new_matrix = []
    for i in range(matrix.shape[1]):
        for j in range(matrix.shape[0]):
            new_matrix.append(matrix[j][i])
    Final = np.array(new_matrix)
    Final = Final.reshape(matrix.shape[1],matrix.shape[0])
    return Final

original_matrix = np.array([[1,2,3],[4,5,6]])
Transposed_matrix = transpose(original_matrix)
print(original_matrix)
print(Transposed_matrix)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [90]:
import webbrowser

def download(urls):
    for k in urls:
        try:
            for i in range(3):
                if webbrowser.open(k):
                    break
        except:
            "Could not download!"
    